### ISSUE TITLE
how to decode received signal

### ISSUE THREAD

**Issue by danialghlm** [ioelectro/hcs-programmer-soft#1]
سلام آقای مهندس وقتتون بخیر.
ممنون از برنامه فوق العاده ای که نوشتید.
من یک ریموت HCS301 دارم و میخوام با استفاده از رسیور 433mhz و اردوینو یک رله کنترل کنم. از کد شما و برنامه شما برای آپلود برنامه روی چیپ HCS301 استفاده کردم، سریال نامبر و key روی آن ریختم.
حالا وقتی میخوام سیگنال دیکد کنم و اردوینو تشخیص بده که ریموت مد نظر کدام است، دچار مشکل شده ام. نمیدونم از چه تابعی برای دیکد کردن باید استفاده کرد؟ خیلی ممنون میشم کمکم کنید تا اینکار انجام بدهم. و چطور میشه سیگنال دریافتی دیکد کرد؟

**Comment by liyanboy74** [comment]
سلام، ممنون.
با توجه به دیتاشیت میتونید فرمت پکت ارسالی HCS301 رو مشاهده کنید.
پکت ارسالی از یک قسمت ثابت و یک قسمت متغیر (رمز شده) تشکیل شده که قسمت متغیر با الگوریتم KeeLoq رمز شده.
کتابخانه کد مربوط به انکود و دیکود الگوریتم KeeLoq (کی لاک) رو میتونید از لینک زیر دریافت کنید:
[https://github.com/liyanboy74/KeeLoq](https://github.com/liyanboy74/KeeLoq)

قبل از استفاده روی میکرو و یا آرداینو، بهتره که کد را روی کامپیوتر تست کنید.
موفق باشید.

**Comment by liyanboy74** [comment]
کتابخانه این قابلیت رو داره که برای کامپایلرهایی که متغیر64 بیتی را پشتیبانی نمیکنند، آن را به صورت دو قسمت32 بیتی شبیه سازی کند.
