### ISSUE TITLE
Verify and read HCS content

### ISSUE THREAD

**Issue by d82k** [ioelectro/hcs-programmer-soft#2]
Hello, this looks very promising!!!
I ordered HCS300 to test with your programmer, the only difference with HCS301 should be the voltage operation (2-6.3V) would this work with your programmer and the arduino setup?
Also I see there is a verification function, is it possible to dump the content of an HCS and recover the information saved previously?
Kind regards,
DK

**Comment by liyanboy74** [comment]
Hi, verification only one time and only immediately after programming is possible!
I checked the hcs300. It has the same programming method and parameters to program, I think it is able to program hcs300 to, but I can't test that.

**Comment by liyanboy74** [comment]
Another difference between hcs300 & hcs301 is:
```
LOW VOLTAGE TRIP POINT
SELECT
The low voltage trip point select bit is used to tell the
HCS301 what VDD level is being used. This information
will be used by the device to determine when to send the
voltage low signal to the receiver. When this bit is set to
a one, the VDD level is assumed to be operating from a
9V or 12V VDD level. If the bit is set low, then the VDD level
is assumed to be 6.0 volts. Refer to Figure 3-1 for voltage
trip point.
```
![image](https://github.com/user-attachments/assets/d1b55b5d-1e4b-4ef2-a72e-3922a20fcad4)

```
LOW VOLTAGE TRIP POINT
SELECT (VLOW SEL)
The low voltage trip point select bit is used to tell the
HCS300 what VDD level is being used. This information
will be used by the device to determine when to send
the voltage low signal to the receiver. When this bit is
set to a one, the VDD level is assumed to be operating
from a 5V or 6V VDD level. If the bit is set low, then the
VDD level is assumed to be 3.0 volts.
```
![image](https://github.com/user-attachments/assets/d4aad7c1-693a-4d7c-8d20-0fee66aa2df2)

​The VDD section on the app for hcs 300, values are different:
![image](https://github.com/user-attachments/assets/6ab35331-f6d3-4b37-af92-07c63075b067)
